CREATE TABLE IF NOT EXISTS contact_messages (
    id SERIAL PRIMARY KEY,

    name VARCHAR(100) NOT NULL,

    email VARCHAR(254) NOT NULL,

    company VARCHAR(150),

    message TEXT NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE
        DEFAULT CURRENT_TIMESTAMP
);